version: '3.8'
services:
  manager:
    build: manager
    ports:
      - '8080:8080'
    expose:
      - '8080'
    environment:
      - PORT=8080
      - WORKER_HOST=worker
      - WORKER_PORT=8080

  worker:
    build: worker
    expose:
      - '8080'
    environment:
      - PORT=8080
      - MANAGER_HOST=manager
      - MANAGER_PORT=8080