task.max-execution-duration=${TASK_EXECUTION_MAX_DURATION}
workers.number=${WORKERS_NUMBER}
spring.data.mongodb.uri=${MONGO_URI}
spring.rabbitmq.host=${RABBIT_HOST}
spring.rabbitmq.port=${RABBIT_PORT}
spring.rabbitmq.username=${RABBIT_USERNAME}
spring.rabbitmq.password=${RABBIT_PASSWORD}
task-parts.queue.name=${TASK_PARTS_QUEUE_NAME}
task-parts-results.queue.name=${TASK_PARTS_RESULTS_QUEUE_NAME}